config/routes.rb
DemoApp::Application.routes.draw do
  resources :space_cats

end

app/models/space_cat.rb
class SpaceCat < ActiveRecord::Base
  attr_accessible :integer, :name, :planet, :planets_visited, :string, :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/space_cats_controller.rb
class SpaceCatsController < ApplicationController
  # GET /space_cats
  # GET /space_cats.json
  def index
    @space_cats = SpaceCat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @space_cats }
    end
  end

  # GET /space_cats/1
  # GET /space_cats/1.json
  def show
    @space_cat = SpaceCat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @space_cat }
    end
  end

  # GET /space_cats/new
  # GET /space_cats/new.json
  def new
    @space_cat = SpaceCat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @space_cat }
    end
  end

  # GET /space_cats/1/edit
  def edit
    @space_cat = SpaceCat.find(params[:id])
  end

  # POST /space_cats
  # POST /space_cats.json
  def create
    @space_cat = SpaceCat.new(params[:space_cat])

    respond_to do |format|
      if @space_cat.save
        format.html { redirect_to @space_cat, notice: 'Space cat was successfully created.' }
        format.json { render json: @space_cat, status: :created, location: @space_cat }
      else
        format.html { render action: "new" }
        format.json { render json: @space_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /space_cats/1
  # PUT /space_cats/1.json
  def update
    @space_cat = SpaceCat.find(params[:id])

    respond_to do |format|
      if @space_cat.update_attributes(params[:space_cat])
        format.html { redirect_to @space_cat, notice: 'Space cat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @space_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /space_cats/1
  # DELETE /space_cats/1.json
  def destroy
    @space_cat = SpaceCat.find(params[:id])
    @space_cat.destroy

    respond_to do |format|
      format.html { redirect_to space_cats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/space_cats_helper.rb
module SpaceCatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/space_cats/_form.html.erb
<%= form_for(@space_cat) do |f| %>
  <% if @space_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space_cat.errors.count, "error") %> prohibited this space_cat from being saved:</h2>

      <ul>
      <% @space_cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :planets_visited %><br />
    <%= f.text_field :planets_visited %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :planet %><br />
    <%= f.text_field :planet %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/space_cats/edit.html.erb
<h1>Editing space_cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @space_cat %> |
<%= link_to 'Back', space_cats_path %>

app/views/space_cats/index.html.erb
<h1>Listing space_cats</h1>

<table>
  <tr>
    <th>Name</th>
    <th>String</th>
    <th>Planets visited</th>
    <th>Integer</th>
    <th>Planet</th>
    <th>String</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @space_cats.each do |space_cat| %>
  <tr>
    <td><%= space_cat.name %></td>
    <td><%= space_cat.string %></td>
    <td><%= space_cat.planets_visited %></td>
    <td><%= space_cat.integer %></td>
    <td><%= space_cat.planet %></td>
    <td><%= space_cat.string %></td>
    <td><%= link_to 'Show', space_cat %></td>
    <td><%= link_to 'Edit', edit_space_cat_path(space_cat) %></td>
    <td><%= link_to 'Destroy', space_cat, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Space cat', new_space_cat_path %>

app/views/space_cats/new.html.erb
<h1>New space_cat</h1>

<%= render 'form' %>

<%= link_to 'Back', space_cats_path %>

app/views/space_cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @space_cat.name %>
</p>

<p>
  <b>String:</b>
  <%= @space_cat.string %>
</p>

<p>
  <b>Planets visited:</b>
  <%= @space_cat.planets_visited %>
</p>

<p>
  <b>Integer:</b>
  <%= @space_cat.integer %>
</p>

<p>
  <b>Planet:</b>
  <%= @space_cat.planet %>
</p>

<p>
  <b>String:</b>
  <%= @space_cat.string %>
</p>


<%= link_to 'Edit', edit_space_cat_path(@space_cat) %> |
<%= link_to 'Back', space_cats_path %>